### PR TITLE
Remove background

### LINKED ISSUE #114: Remove Image Background (local, in-browser AI)
### Short Description
Add a tool that removes an image's background entirely in the browser using a local AI segmentation model (WebGPU, with a WASM fallback). This is the single most-requested image feature of 2026 (remove.bg, Photoroom, Canva) — and every one of those uploads your photo to a server. Doing it locally is a flagship privacy differentiator for DoxDock.

### Scope
- Follow the plugin pattern: a self-contained `src/operations/<id>/{meta.js,index.jsx,helpers.js}` folder (auto-discovered — no central wiring), reusing shared pieces (`Dropzone`, `useJob`, `Note`, `Progress`, `ImageResult`/`ResultGallery`, `imageCanvas`).
- New operation `src/operations/remove-background/`. Run a small segmentation model (e.g. a distilled u2net/rembg or MODNet) via `onnxruntime-web` or Transformers.js, preferring WebGPU with a WASM fallback. Output a transparent PNG.
- CRITICAL: the model weights and the ONNX/WASM runtime MUST be bundled as local assets served from the app's own origin. Transformers.js / onnxruntime-web default to fetching weights from a CDN (HuggingFace), which our CSP forbids — configure the library to load everything from local files so the tool works fully offline.
- Show per-image progress (models are slow to load/run) and support batch. Handle "WebGPU unavailable" by falling back to WASM with a clear note.

### Acceptance criteria
- [ ] Removing the background produces a transparent-background PNG.
- [ ] No network requests happen during load or processing (verify with the network panel) — the model loads from the app itself.
- [ ] Progress is shown; the tool degrades gracefully when WebGPU is unavailable.

### PR DESCRIPTION
**Pull request by Debdip2003**
**Issue Number:**
Closes #114 — Add Remove Background tool using local AI segmentation model

**Summary of Changes:**
Added a new "Remove Background" tool under src/operations/remove-background/:

helpers.js — loads the bundled U²NetP ONNX model locally using onnxruntime-web, creates and caches a single inference session, preprocesses images into normalized tensors, runs AI-based foreground segmentation entirely in the browser, converts the predicted mask into an alpha channel, applies it to the original image, and exports a transparent PNG while preserving the original image resolution. Also reports progress throughout the processing pipeline.
index.jsx — provides the UI with a drag-and-drop file picker, background removal action, progress indicator, error handling, and result preview. Uses the shared ImageResult component to display the transparent output along with before/after file size comparison.
meta.js — registers the tool in the sidebar under the Image category with the appropriate metadata and operation order.
Local AI model support — bundles the U²NetP ONNX model and ONNX Runtime WASM files locally under the application's public assets. The model is loaded entirely from the application's own origin, enabling complete offline processing with no external API calls or CDN dependencies.
WebAssembly inference — configures onnxruntime-web to load the local WASM runtime from /ort/, ensuring background removal runs completely in the browser without uploading any user images.

**Testing / Validation:**
Verified successful background removal on PNG and JPEG images.
Confirmed the output is exported as a transparent PNG while preserving the original image dimensions.
Verified the ONNX model and WASM runtime load entirely from local assets.
Confirmed zero external network requests during model loading and image processing (DevTools → Network tab).
Tested the tool completely offline after the initial application load.
Verified progress updates are displayed throughout model loading, inference, mask generation, and image encoding.
Confirmed appropriate error messages are shown for unsupported or corrupt image files.
Verified the model session is reused for subsequent images to avoid repeated model loading and improve performance.

**Before:**
This feature did not exist in the application.

**After:**
The new Remove Background tool is available under the Image category, allowing users to remove image backgrounds entirely offline using a locally bundled AI model and download the result as a transparent PNG with no data leaving the device.

### CODE REVIEW

**Comment by mithun-srinivas** [comment]
@Debdip2003 this is a seriously ambitious first cut and the approach is spot on - bundling the u2netp model and the onnxruntime-web wasm locally and loading them same-origin is exactly how we keep the zero-network promise, and the Static Network Scan passing proves it. nice touch adding the COOP/COEP headers for SharedArrayBuffer too.

it is failing three required checks though, and they are connected:

1. **Build + Lint (the real blocker)** - `vite build` is almost certainly choking on `onnxruntime-web`. it usually needs a little Vite config: add `optimizeDeps: { exclude: ['onnxruntime-web'] }`, and make sure the ORT wasm/worker files are served as-is (they are in `public/`, which is the right place). could you get `npm run build` passing locally first? that is the thing to fix.

2. **Check Bundle Size** - `onnxruntime-web` is a big JS dependency and the size budget was never set up for a multi-MB AI runtime. since this tool is lazy-loaded into its own chunk, it should not count against the initial-load budget - that is partly on us to adjust the size-limit config to exclude the lazy AI chunk. do not worry about this one for now: get the build green and we will sort the budget from our side.

3. **Automated A11y + E2E** - these serve the built app, so they are just failing because the build is failing. they should go green on their own once #1 is fixed.

so the one thing to chase is the Vite build. this is exactly the headline feature we have been wanting, so I am really keen to get it in - shout if you get stuck on the onnxruntime config and I will dig in with you. great work so far 🙌

**Comment by Debdip2003** [comment]
HI @mithun-srinivas , can you help me with this issue, I have tried and the build is doing great locally but here it is failing, I personally cannot find out the reason, can you please hop on this one?

Locally:
image

**Comment by mithun-srinivas** [comment]
good news @Debdip2003 - it is **not** your code 🎉. i pulled the CI build log and the actual error is this:

```
Error: Cannot find module @rollup/rollup-linux-x64-gnu.
npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828).
```

that is the well-known npm + rollup optional-dependency bug. it builds fine on your machine because you are on macOS, where rollup uses `@rollup/rollup-darwin-*` - but when you added `onnxruntime-web` and regenerated `package-lock.json`, the lockfile ended up **without the linux rollup binary**. CI runs on linux and does `npm ci` (a strict install straight from the lockfile), so it cannot find `@rollup/rollup-linux-x64-gnu` and the build dies before it ever touches your background-removal code.

the fix is to regenerate the lockfile cleanly on top of the latest main:

```bash
git fetch origin
git rebase origin/main            # or: git merge origin/main
rm -rf node_modules package-lock.json
npm install                       # regenerates a lockfile with ALL platform binaries
git add package-lock.json
git commit -m "fix: regenerate lockfile with all platform rollup binaries"
git push
```

that puts the full set of `@rollup/rollup-*` optional deps back into `package-lock.json`, and CI's `npm ci` on linux will find the one it needs.

once the build is green, the **A11y** and **E2E** checks will pass on their own (they were only failing because the build was). the one remaining check will be **Check Bundle Size**, and that one is on us - the onnxruntime chunk needs a budget bump, which i will sort from our side.

genuinely nice work - the hard part (the actual segmentation + local model/wasm bundling) is done and correct. this is just a packaging hiccup. 🙌

**Comment by Debdip2003** [comment]
Hey, FYI, I'm not on MacOS, I'm using Windows 11 laptop, but still the build is running fine.

**Comment by Debdip2003** [comment]
@mithun-srinivas I have tried the given solution but still the issue is persisting, please look into this issue and merge the code asap if all the criterias have been fullfilled.

**Comment by mithun-srinivas** [comment]
@Debdip2003 jumped on it as promised 👋 — good news: your actual background-removal code and the local model/wasm bundling were fine. there was a stack of packaging + merge issues hiding *behind* the `npm ci` error, so I pushed a commit to your branch (maintainer edit) fixing them:

1. **`package-lock.json`** — regenerated with npm 11 so it now contains **all** the `@rollup/rollup-*` platform binaries (the linux one CI needs was missing). that was the `npm ci` failure. side note: it was actually deleted on the branch, which is why my earlier fix didn't take.
2. **`vite.config.js`** — the `optimizeDeps: { exclude: ['onnxruntime-web'] }` block was never closed with a `}`, so it swallowed the `test`/`plugins` config and the build failed with a syntax error. closed it. (this is why it wouldn't build even with deps installed.)
3. **duplicate imports** — a few image tools (greyscale, invert, watermark, redact) had `IMAGE_FORMATS_HINT` / `imageCanvas` imported twice, left over from merging `main`. removed the dupes.

with those, `npm ci` + `vite build` + prerender all pass locally and the network scan is clean. CI is re-running now.

the one check that will still be red is **Check Bundle Size** — that's expected and it's on us: the onnxruntime runtime + model is a big lazy chunk and the size budget was never set up for it. I'll adjust that from our side so it doesn't block you.

genuinely nice work on the hard part 🙌

**Comment by mithun-srinivas** [comment]
this is a big one 🎉 — DoxDock's **first on-device AI tool**: background removal running entirely in the browser, with the model and ONNX runtime bundled locally, nothing ever uploaded. all six checks are green.

thank you for pushing through the packaging pain @Debdip2003 — the actual AI work here (the segmentation, the local model/wasm bundling, the COOP/COEP setup) is genuinely excellent, and it's exactly the kind of thing that shows off what "100% in your browser" can do. merging! 🙌

(one small follow-up for later, not urgent: the ONNX wasm currently ships twice — once in `public/ort` and once emitted into the JS assets — so there's a bit of dedup to be had. I'll open a tidy-up issue.)
